export const TIPOS_PRODUTO = [
  'BASICA', 'BLAZER', 'BLUSA', 'BLUSAO', 'BLUSAO MO', 'BLUSAO TRI',
  'BLUSINHA', 'BLUSINHA TE', 'BODY', 'BOLERO', 'BOXER', 'CALCA',
  'CALCA JE', 'CALCA MO', 'CALCINHA', 'CALCOLA', 'CAMISA', 'CAMISETA',
  'CAMISETA PI', 'CAMISETA TE', 'CAMISETE', 'CAMISOLA', 'CASACO',
  'CASACO MO', 'CASACO TRI', 'CASAQUINHO', 'CEROULA', 'CINTA CALCA',
  'COLETE', 'CONJ.', 'CONJ. BATIZADO', 'CONJ. LING', 'CUECA', 'FIO',
  'JAQUETA', 'JAQUETA JE', 'KIMONO', 'KIT CUECA', 'KIT MEIA', 'LEG',
  'MEIA', 'MEIA CALCA', 'MEIAO', 'MIJAO', 'MODELADOR', 'PAGAO',
  'PIJAMA', 'POLO', 'PONCHO', 'ROUPAO', 'SAIA', 'SAMBA CANCAO',
  'SUNGA', 'SUTIA', 'TANGAO', 'TERNO', 'TIP TOP', 'VESTIDO',
]
